""" version which can be consumed from within the module """
VERSION_STR = "0.0.18"
DESCRIPTION = "pymakehelper helps doing things with the make system"
APP_NAME = "pymakehelper"
LOGGER_NAME = "pymakehelper"
